export const matches = {
  "03.09.2023": {
    events: [
      {
        result: [
          {
            event_id: 39686729,
            market_id: 1254609244,
            market_name: "Перемога",
            outcomes: [
              {
                outcome_coef: 1.69,
                outcome_name: "Liverpool",
                outcome_short_name: "1",
                flag: "🏴󠁧󠁢󠁥󠁮󠁧󠁿",
              },
              {
                outcome_coef: 4.5,
                outcome_name: "Нічия",
                outcome_short_name: "X",
              },
              {
                outcome_coef: 4.7,
                outcome_name: "Aston Villa",
                outcome_short_name: "2",
                flag: "🏴󠁧󠁢󠁥󠁮󠁧󠁿",
              },
            ],
          },
          {},
          {
            event_id: 39686729,
            market_id: 1254609284,
            market_name: "Точний рахунок",
            market_suspend: false,
            market_template_id: 520,
            market_template_view_id: 6,
            market_template_weigh: 19,
            outcomes: [
              {
                outcome_coef: 3.2,
                outcome_name: "Any other",
                outcome_param: "Any other outcome",
                outcome_short_name: "Any other",
              },
              {
                outcome_coef: 28,
                outcome_name: "0:0",
                outcome_param: "0:0",
                outcome_short_name: "0:0",
              },
              {
                outcome_coef: 8.8,
                outcome_name: "1:1",
                outcome_param: "1:1",
                outcome_short_name: "1:1",
              },
              {
                outcome_coef: 11.5,
                outcome_name: "2:2",
                outcome_param: "2:2",
                outcome_short_name: "2:2",
              },
              {
                outcome_coef: 12.5,
                outcome_name: "1:0",
                outcome_param: "1:0",
                outcome_short_name: "1:0",
              },
              {
                outcome_coef: 10.5,
                outcome_name: "2:0",
                outcome_param: "2:0",
                outcome_short_name: "2:0",
              },
              {
                outcome_coef: 14,
                outcome_name: "3:0",
                outcome_param: "3:0",
                outcome_short_name: "3:0",
              },
              {
                outcome_coef: 8.6,
                outcome_name: "2:1",
                outcome_param: "2:1",
                outcome_short_name: "2:1",
              },
              {
                outcome_coef: 11,
                outcome_name: "3:1",
                outcome_param: "3:1",
                outcome_short_name: "3:1",
              },
              {
                outcome_coef: 17.5,
                outcome_name: "3:2",
                outcome_param: "3:2",
                outcome_short_name: "3:2",
              },
              {
                outcome_coef: 21,
                outcome_name: "0:1",
                outcome_param: "0:1",
                outcome_short_name: "0:1",
              },
              {
                outcome_coef: 32,
                outcome_name: "0:2",
                outcome_param: "0:2",
                outcome_short_name: "0:2",
              },
              {
                outcome_coef: 70,
                outcome_name: "0:3",
                outcome_param: "0:3",
                outcome_short_name: "0:3",
              },
              {
                outcome_coef: 15,
                outcome_name: "1:2",
                outcome_param: "1:2",
                outcome_short_name: "1:2",
              },
              {
                outcome_coef: 33,
                outcome_name: "1:3",
                outcome_param: "1:3",
                outcome_short_name: "1:3",
              },
              {
                outcome_coef: 31,
                outcome_name: "2:3",
                outcome_param: "2:3",
                outcome_short_name: "2:3",
              },
            ],
          },
        ],
      },
      {
        result: [
          {
            event_id: 39686723,
            market_id: 1254607686,
            market_name: "Перемога",
            market_suspend: false,
            market_template_id: 1,
            market_template_view_id: 2,
            market_template_view_schema: null,
            market_template_weigh: 5,
            outcomes: [
              {
                outcome_coef: 1.83,
                outcome_name: "Arsenal",
                outcome_param: null,
                outcome_short_name: "1",
                flag: "🏴󠁧󠁢󠁥󠁮󠁧󠁿",
              },
              {
                outcome_coef: 4.25,
                outcome_name: "Нічия",
                outcome_param: "Draw",
                outcome_short_name: "X",
              },
              {
                outcome_coef: 4.55,
                outcome_name: "Man United",
                outcome_param: null,
                outcome_short_name: "2",
                flag: "🏴󠁧󠁢󠁥󠁮󠁧󠁿",
              },
            ],
          },
          {},
          {
            event_id: 39686723,
            market_id: 1254607725,
            market_name: "Точний рахунок",
            market_suspend: false,
            market_template_id: 520,
            market_template_view_id: 6,
            market_template_weigh: 19,
            outcomes: [
              {
                outcome_coef: 3.95,
                outcome_name: "Any other",
                outcome_param: "Any other outcome",
                outcome_short_name: "Any other",
                "outcome_ty  pe_id": 356,
              },
              {
                outcome_coef: 21,
                outcome_name: "0:0",
                outcome_param: "0:0",
                outcome_short_name: "0:0",
              },
              {
                outcome_coef: 7.7,
                outcome_name: "1:1",
                outcome_param: "1:1",
                outcome_short_name: "1:1",
              },
              {
                outcome_coef: 11.5,
                outcome_name: "2:2",
                outcome_param: "2:2",
                outcome_short_name: "2:2",
              },
              {
                outcome_coef: 10.5,
                outcome_name: "1:0",
                outcome_param: "1:0",
                outcome_short_name: "1:0",
              },
              {
                outcome_coef: 9.8,
                outcome_name: "2:0",
                outcome_param: "2:0",
                outcome_short_name: "2:0",
              },
              {
                outcome_coef: 14.5,
                outcome_name: "3:0",
                outcome_param: "3:0",
                outcome_short_name: "3:0",
              },
              {
                outcome_coef: 8.5,
                outcome_name: "2:1",
                outcome_param: "2:1",
                outcome_short_name: "2:1",
              },
              {
                outcome_coef: 11.5,
                outcome_name: "3:1",
                outcome_param: "3:1",
                outcome_short_name: "3:1",
              },
              {
                outcome_coef: 20,
                outcome_name: "3:2",
                outcome_param: "3:2",
                outcome_short_name: "3:2",
              },
              {
                outcome_coef: 17.5,
                outcome_name: "0:1",
                outcome_param: "0:1",
                outcome_short_name: "0:1",
              },
              {
                outcome_coef: 26,
                outcome_name: "0:2",
                outcome_param: "0:2",
                outcome_short_name: "0:2",
              },
              {
                outcome_coef: 65,
                outcome_name: "0:3",
                outcome_param: "0:3",
                outcome_short_name: "0:3",
              },
              {
                outcome_coef: 14,
                outcome_name: "1:2",
                outcome_param: "1:2",
                outcome_short_name: "1:2",
              },
              {
                outcome_coef: 32,
                outcome_name: "1:3",
                outcome_param: "1:3",
                outcome_short_name: "1:3",
              },
              {
                outcome_coef: 34,
                outcome_name: "2:3",
                outcome_param: "2:3",
                outcome_short_name: "2:3",
              },
            ],
          },
        ],
      },
      {
        result: [
          {
            event_id: 39624860,
            market_id: 1254613741,
            market_name: "Перемога",
            market_suspend: false,
            market_template_id: 1,
            market_template_view_id: 2,
            market_template_view_schema: null,
            market_template_weigh: 5,
            outcomes: [
              {
                outcome_coef: 3.1,
                outcome_name: "Union",
                outcome_param: null,
                outcome_short_name: "1",
                flag: "🇩🇪",
              },
              {
                outcome_coef: 3.55,
                outcome_name: "Нічия",
                outcome_param: "Draw",
                outcome_short_name: "X",
              },
              {
                outcome_coef: 2.37,
                outcome_name: "RB Leipzig",
                outcome_param: null,
                outcome_short_name: "2",
                flag: "🇩🇪",
              },
            ],
          },
          {},
          {
            event_id: 39624860,
            market_id: 1254613778,
            market_name: "Точний рахунок",
            outcomes: [
              {
                outcome_coef: 7,
                outcome_name: "Any other",
                outcome_param: "Any other outcome",
                outcome_short_name: "Any other",
              },
              {
                outcome_coef: 9.3,
                outcome_name: "0:0",
                outcome_param: "0:0",
                outcome_short_name: "0:0",
              },
              {
                outcome_coef: 6.4,
                outcome_name: "1:1",
                outcome_param: "1:1",
                outcome_short_name: "1:1",
              },
              {
                outcome_coef: 13,
                outcome_name: "2:2",
                outcome_param: "2:2",
                outcome_short_name: "2:2",
              },
              {
                outcome_coef: 9.9,
                outcome_name: "1:0",
                outcome_param: "1:0",
                outcome_short_name: "1:0",
              },
              {
                outcome_coef: 15,
                outcome_name: "2:0",
                outcome_param: "2:0",
                outcome_short_name: "2:0",
              },
              {
                outcome_coef: 36,
                outcome_name: "3:0",
                outcome_param: "3:0",
                outcome_short_name: "3:0",
              },
              {
                outcome_coef: 10.5,
                outcome_name: "2:1",
                outcome_param: "2:1",
                outcome_short_name: "2:1",
              },
              {
                outcome_coef: 24,
                outcome_name: "3:1",
                outcome_param: "3:1",
                outcome_short_name: "3:1",
              },
              {
                outcome_coef: 34,
                outcome_name: "3:2",
                outcome_param: "3:2",
                outcome_short_name: "3:2",
              },
              {
                outcome_coef: 8.5,
                outcome_name: "0:1",
                outcome_param: "0:1",
                outcome_short_name: "0:1",
              },
              {
                outcome_coef: 11,
                outcome_name: "0:2",
                outcome_param: "0:2",
                outcome_short_name: "0:2",
              },
              {
                outcome_coef: 22,
                outcome_name: "0:3",
                outcome_param: "0:3",
                outcome_short_name: "0:3",
              },
              {
                outcome_coef: 9.1,
                outcome_name: "1:2",
                outcome_param: "1:2",
                outcome_short_name: "1:2",
              },
              {
                outcome_coef: 17.5,
                outcome_name: "1:3",
                outcome_param: "1:3",
                outcome_short_name: "1:3",
              },
              {
                outcome_coef: 29,
                outcome_name: "2:3",
                outcome_param: "2:3",
                outcome_short_name: "2:3",
              },
            ],
          },
        ],
      },
      {
        result: [
          {
            event_id: 39498666,
            market_id: 1254624649,
            market_name: "Перемога",
            market_suspend: false,
            market_template_id: 1,
            market_template_view_id: 2,
            market_template_view_schema: null,
            market_template_weigh: 5,
            outcomes: [
              {
                outcome_coef: 1.49,
                outcome_name: "Atletico M",
                outcome_param: null,
                outcome_short_name: "1",
                flag: "🇪🇸",
              },
              {
                outcome_coef: 4.6,
                outcome_name: "Нічия",
                outcome_param: "Draw",
                outcome_short_name: "X",
              },
              {
                outcome_coef: 7.2,
                outcome_name: "Sevilla",
                outcome_param: null,
                outcome_short_name: "2",
                flag: "🇪🇸",
              },
            ],
          },
          {},
          {
            event_id: 39498666,
            market_id: 1254624692,
            market_name: "Точний рахунок",
            outcomes: [
              {
                outcome_coef: 4.6,
                outcome_name: "Any other",
                outcome_param: "Any other outcome",
                outcome_short_name: "Any other",
              },
              {
                outcome_coef: 10,
                outcome_name: "0:0",
                outcome_param: "0:0",
                outcome_short_name: "0:0",
              },
              {
                outcome_coef: 8.4,
                outcome_name: "1:1",
                outcome_param: "1:1",
                outcome_short_name: "1:1",
              },
              {
                outcome_coef: 18.5,
                outcome_name: "2:2",
                outcome_param: "2:2",
                outcome_short_name: "2:2",
              },
              {
                outcome_coef: 6.9,
                outcome_name: "1:0",
                outcome_param: "1:0",
                outcome_short_name: "1:0",
              },
              {
                outcome_coef: 6.5,
                outcome_name: "2:0",
                outcome_param: "2:0",
                outcome_short_name: "2:0",
              },
              {
                outcome_coef: 9.4,
                outcome_name: "3:0",
                outcome_param: "3:0",
                outcome_short_name: "3:0",
              },
              {
                outcome_coef: 8.2,
                outcome_name: "2:1",
                outcome_param: "2:1",
                outcome_short_name: "2:1",
              },
              {
                outcome_coef: 11.5,
                outcome_name: "3:1",
                outcome_param: "3:1",
                outcome_short_name: "3:1",
              },
              {
                outcome_coef: 29,
                outcome_name: "3:2",
                outcome_param: "3:2",
                outcome_short_name: "3:2",
              },
              {
                outcome_coef: 17,
                outcome_name: "0:1",
                outcome_param: "0:1",
                outcome_short_name: "0:1",
              },
              {
                outcome_coef: 41,
                outcome_name: "0:2",
                outcome_param: "0:2",
                outcome_short_name: "0:2",
              },
              {
                outcome_coef: 100,
                outcome_name: "0:3",
                outcome_param: "0:3",
                outcome_short_name: "0:3",
              },
              {
                outcome_coef: 20,
                outcome_name: "1:2",
                outcome_param: "1:2",
                outcome_short_name: "1:2",
              },
              {
                outcome_coef: 70,
                outcome_name: "1:3",
                outcome_param: "1:3",
                outcome_short_name: "1:3",
              },
              {
                outcome_coef: 75,
                outcome_name: "2:3",
                outcome_param: "2:3",
                outcome_short_name: "2:3",
              },
            ],
          },
        ],
      },
      {
        result: [
          {
            event_id: 39735298,
            market_id: 1254608831,
            market_name: "Перемога",
            market_suspend: false,
            market_template_id: 1,
            market_template_view_id: 2,
            market_template_view_schema: null,
            market_template_weigh: 5,
            outcomes: [
              {
                outcome_coef: 1.69,
                outcome_name: "Inter M",
                outcome_param: null,
                outcome_short_name: "1",
                flag: "🇮🇹",
              },
              {
                outcome_coef: 4.1,
                outcome_name: "Нічия",
                outcome_param: "Draw",
                outcome_short_name: "X",
              },
              {
                outcome_coef: 5.3,
                outcome_name: "Fiorentina",
                outcome_param: null,
                outcome_short_name: "2",
                flag: "🇮🇹",
              },
            ],
          },
          {},
          {
            event_id: 39735298,
            market_id: 1254608869,
            market_name: "Точний рахунок",
            outcomes: [
              {
                outcome_coef: 5.2,
                outcome_name: "Any other",
                outcome_param: "Any other outcome",
                outcome_short_name: "Any other",
              },
              {
                outcome_coef: 10,
                outcome_name: "0:0",
                outcome_param: "0:0",
                outcome_short_name: "0:0",
              },
              {
                outcome_coef: 7.4,
                outcome_name: "1:1",
                outcome_param: "1:1",
                outcome_short_name: "1:1",
              },
              {
                outcome_coef: 15,
                outcome_name: "2:2",
                outcome_param: "2:2",
                outcome_short_name: "2:2",
              },
              {
                outcome_coef: 7.4,
                outcome_name: "1:0",
                outcome_param: "1:0",
                outcome_short_name: "1:0",
              },
              {
                outcome_coef: 7.6,
                outcome_name: "2:0",
                outcome_param: "2:0",
                outcome_short_name: "2:0",
              },
              {
                outcome_coef: 12,
                outcome_name: "3:0",
                outcome_param: "3:0",
                outcome_short_name: "3:0",
              },
              {
                outcome_coef: 8.2,
                outcome_name: "2:1",
                outcome_param: "2:1",
                outcome_short_name: "2:1",
              },
              {
                outcome_coef: 12.5,
                outcome_name: "3:1",
                outcome_param: "3:1",
                outcome_short_name: "3:1",
              },
              {
                outcome_coef: 27,
                outcome_name: "3:2",
                outcome_param: "3:2",
                outcome_short_name: "3:2",
              },
              {
                outcome_coef: 14.5,
                outcome_name: "0:1",
                outcome_param: "0:1",
                outcome_short_name: "0:1",
              },
              {
                outcome_coef: 28,
                outcome_name: "0:2",
                outcome_param: "0:2",
                outcome_short_name: "0:2",
              },
              {
                outcome_coef: 85,
                outcome_name: "0:3",
                outcome_param: "0:3",
                outcome_short_name: "0:3",
              },
              {
                outcome_coef: 16,
                outcome_name: "1:2",
                outcome_param: "1:2",
                outcome_short_name: "1:2",
              },
              {
                outcome_coef: 47,
                outcome_name: "1:3",
                outcome_param: "1:3",
                outcome_short_name: "1:3",
              },
              {
                outcome_coef: 50,
                outcome_name: "2:3",
                outcome_param: "2:3",
                outcome_short_name: "2:3",
              },
            ],
          },
        ],
      },
      {
        result: [
          {
            event_id: 39648969,
            market_id: 1254609365,
            market_name: "Перемога",
            market_suspend: false,
            market_template_id: 1,
            market_template_view_id: 2,
            market_template_view_schema: null,
            market_template_weigh: 5,
            outcomes: [
              {
                outcome_coef: 5.6,
                outcome_name: "Lion",
                outcome_param: null,
                outcome_short_name: "1",
                flag: "🇫🇷",
              },
              {
                outcome_coef: 4.9,
                outcome_name: "Нічия",
                outcome_param: "Draw",
                outcome_short_name: "X",
              },
              {
                outcome_coef: 1.55,
                outcome_name: "PSG",
                outcome_param: null,
                outcome_short_name: "2",
                flag: "🇫🇷",
              },
            ],
          },
          {},
          {
            event_id: 39648969,
            market_id: 1254609394,
            market_name: "Точний рахунок",
            outcomes: [
              {
                outcome_coef: 3.2,
                outcome_name: "Any other",
                outcome_param: "Any other outcome",
                outcome_short_name: "Any other",
              },
              {
                outcome_coef: 27,
                outcome_name: "0:0",
                outcome_param: "0:0",
                outcome_short_name: "0:0",
              },
              {
                outcome_coef: 9.3,
                outcome_name: "1:1",
                outcome_param: "1:1",
                outcome_short_name: "1:1",
              },
              {
                outcome_coef: 13,
                outcome_name: "2:2",
                outcome_param: "2:2",
                outcome_short_name: "2:2",
              },
              {
                outcome_coef: 22,
                outcome_name: "1:0",
                outcome_param: "1:0",
                outcome_short_name: "1:0",
              },
              {
                outcome_coef: 37,
                outcome_name: "2:0",
                outcome_param: "2:0",
                outcome_short_name: "2:0",
              },
              {
                outcome_coef: 95,
                outcome_name: "3:0",
                outcome_param: "3:0",
                outcome_short_name: "3:0",
              },
              {
                outcome_coef: 16.5,
                outcome_name: "2:1",
                outcome_param: "2:1",
                outcome_short_name: "2:1",
              },
              {
                outcome_coef: 42,
                outcome_name: "3:1",
                outcome_param: "3:1",
                outcome_short_name: "3:1",
              },
              {
                outcome_coef: 38,
                outcome_name: "3:2",
                outcome_param: "3:2",
                outcome_short_name: "3:2",
              },
              {
                outcome_coef: 11,
                outcome_name: "0:1",
                outcome_param: "0:1",
                outcome_short_name: "0:1",
              },
              {
                outcome_coef: 9.2,
                outcome_name: "0:2",
                outcome_param: "0:2",
                outcome_short_name: "0:2",
              },
              {
                outcome_coef: 12,
                outcome_name: "0:3",
                outcome_param: "0:3",
                outcome_short_name: "0:3",
              },
              {
                outcome_coef: 8.3,
                outcome_name: "1:2",
                outcome_param: "1:2",
                outcome_short_name: "1:2",
              },
              {
                outcome_coef: 10,
                outcome_name: "1:3",
                outcome_param: "1:3",
                outcome_short_name: "1:3",
              },
              {
                outcome_coef: 18.5,
                outcome_name: "2:3",
                outcome_param: "2:3",
                outcome_short_name: "2:3",
              },
            ],
          },
        ],
      },
    ],
  },
};
