export const tournamentsMap = {
  "Premier League": "england",
  "EFL Cup": "england",
  "FA Cup": "england",
  Championship: "england",
  Bundesliga: "germany",
  "Champions League": "euroCups",
  "Europe League": "euroCups",
  "Euro 2024. Qualifying": "international",
  "Euro 2024. Germany": "international",
  "Copa America 2024. USA": "international",
  "La Liga": "spain",
  "Spain Super Cup": "spain",
  "Copa del Rey": "spain",
  "Ligue 1": "france",
  "Serie A": "italy",
  "Coppa Italia": "italy",
  Supercoppa: "italy",
};
